### ISSUE TITLE
Optimisations

### ISSUE THREAD

**Issue by peryomin** [peryomin/TicTacToe#9]
Tasklist:
- [x] #10 Make state mutable
- [x] #11 Add transposition table in minimax
- [x] #12 Add genetic algorithm for AI
